name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:

  test:
    name: Run tests
    uses: ./.github/workflows/reusable/run-tests.yml

  build:
    name: Run build
    uses: ./.github/workflows/reusable/run-build.yml

  msrv:
    name: Check MSRV
    strategy:
      matrix:
        toolchain: [ '1.65.0' ]
        target: [ 'x86_64-unknown-linux-gnu', 'aarch64-unknown-linux-gnu' ]
    uses: ./.github/workflows/reusable/check-msrv.yml
    with:
      toolchain: ${{ matrix.toolchain }}
      target: ${{ matrix.target }}
    
  nix-flake:
<<<<<<< HEAD
    name: nix-flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org
    - run: nix flake check
    - run: nix build
=======
    name: Nix Flake
    uses: ./.github/workflows/reusable/nix-flake.yml
>>>>>>> main
